initializer_task:
  description: >
    Decode the requirements of the user
    Think logically about {_field} and find its granular building blocks.
    Right now you are asked "{_input}" based on this what would you suggest the user to search online.
  expected_output: >
    Just a simple list of 5 web search topics about {_input}, with nothing else
    No need to number the questions
  agent: initializer
  output_file: report.md

  prompt_examples:
    input: Teach me python.
    output: |
      - What is python.
      - How is python different from other languages.
      - What are basic constituents of python.
      - Simple programs with explanation in python.
      - Must know about python.